# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
chat:
  art: false
early_access: true
language: ja-JP
reviews:
  poem: false
  profile: chill
  request_changes_workflow: true
