packages:
  - apps/*
  - packages/*
  - profile
  - renovate-config
  - scripts/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@next/*'
  - eslint-config-next
  - next
  - renovate
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
savePrefix: ''
