packages:
  - apps/*
  - packages/*
  - profile
  - renovate-config

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@next/*'
  - '@sanity/*'
  - eslint-config-next
  - next
  - next-sanity
  - renovate
  - sanity
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
savePrefix: ''
