packages:
  - apps/*
  - packages/*
  - profile
  - renovate-config

catalog:
  '@next/mdx': 16.2.6
  next: 16.2.6
  typescript: 6.0.3

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  shape: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@next/*'
  - eslint-config-next
  - next
  - renovate
savePrefix: ''
